const projects = [
    {
      id: 1,
      title: "HeatUp App",
      subtitle: "Lead Full-Stack Developer & Project Manager",
      description: "Mobile event application built with Flutter. Fluid, high-performance interface with real-time database and authentication via Supabase. Currently in production.",
      longDescription: "Led the complete full-stack development of a mobile event application using Flutter. Designed the navigation architecture and state management (Bloc/Provider) to ensure a frictionless user experience. Integrated Supabase for authentication and real-time data. Currently serving users in production in Mexico.",
      technologies: ["Flutter", "Dart", "Supabase", "REST API"],
      categories: ["production", "full-stack"],
      liveUrl: "https://app.heatup.com.mx/",
      githubUrl: null,
      featured: true,
      date: "December 2025 – Present",
    },
    {
      id: 2,
      title: "Jira Clone — Project Manager",
      subtitle: "Project Manager & Lead Developer",
      description: "Full project management web app built with React and TypeScript. Microservices architecture, CI/CD pipeline with Docker, developed for Mahindra.",
      longDescription: "Led development of a Jira-style project manager using SCRUM methodology. Built with React and TypeScript, focused on complete workflow and demonstrating microservices architecture. Acted as Product Owner, translating client needs into development plans. Implemented a CI/CD pipeline with Docker deployment.",
      technologies: ["React", "TypeScript", "Docker", "Microservices"],
      categories: ["client", "full-stack", "productowner"],
      liveUrl: null,
      githubUrl: null,
      featured: true,
      date: "January 2026 – Present",
    },
    {
      id: 3,
      title: "Clínica Nova — iOS Logistics App",
      subtitle: "iOS Developer & Product Owner",
      description: "Native iPad/iPhone app for ambulance logistics. Complex data visualization dashboards, secure JWT authentication, and containerized API communication.",
      longDescription: "Developed a native iOS application for Clínica Nova focused on ambulance logistics management. Created complex data visualization dashboards and secure authentication screens optimizing workflow between administrators and drivers. Implemented JWT for cybersecurity and containerized API communication. Acted as Product Owner using SCRUM.",
      technologies: ["Swift", "iOS", "JWT", "REST API"],
      categories: ["client", "productowner"],
      liveUrl: null,
      githubUrl: null,
      featured: true,
      date: "August – December 2025",
    },
    {
      id: 4,
      title: "HackMty — Optimization Solution",
      subtitle: "Full-Stack Developer",
      description: "Full-stack optimization solution for Gategroup built at HackMty 2025. React frontend with a Python REST API backend.",
      longDescription: "Developed an optimization solution for Gategroup during HackMty 2025. Built a full-stack web application with a React frontend and a Python REST API backend. The solution tackled a real logistics optimization problem under hackathon time pressure.",
      technologies: ["React", "Python", "REST API"],
      categories: ["hackathon", "full-stack"],
      liveUrl: null,
      githubUrl: "https://github.com/javierlcastillo/smartIntelligence-by-MJandTheMonstars",
      featured: false,
      date: "October 2025",
    },
    {
      id: 5,
      title: "Vehicle Flow Simulation",
      subtitle: "ML Developer",
      description: "Reinforcement learning simulation of vehicle traffic at the Garza Sada roundabout in Monterrey. Python RL model with Unity visualization.",
      longDescription: "Developed a vehicle traffic flow simulation at the Garza Sada roundabout using reinforcement learning in Python. Built visual representation with Unity. The model learns optimal traffic light timing to reduce congestion through trial and reward.",
      technologies: ["Python", "Reinforcement Learning", "Unity"],
      categories: ["research", "aiml"],
      liveUrl: null,
      githubUrl: null,
      featured: false,
      date: "August – September 2025",
    },
    {
      id: 6,
      title: "Gerontological Health Platform",
      subtitle: "Web Developer",
      description: "Web platform for monitoring the health of older adults. Minimalist accessible design with React, Tailwind CSS, and Firebase.",
      longDescription: "Built a web platform for the Nuevo León government to monitor the health of senior citizens. Implemented a minimalist and accessible design system with Tailwind CSS, prioritizing readability and ease of use for elderly users. Used Firebase for data management.",
      technologies: ["React", "Tailwind CSS", "Firebase"],
      categories: ["client", "full-stack"],
      liveUrl: null,
      githubUrl: null,
      featured: false,
      date: "January – February 2025",
    },
  ];
  
  export default projects;